-- MySQL Script generated by MySQL Workbench
-- Seg 24 Jun 2019 09:13:21 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RafaelVendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RafaelVendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RafaelVendas` DEFAULT CHARACTER SET utf8 ;
USE `RafaelVendas` ;

-- -----------------------------------------------------
-- Table `RafaelVendas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RafaelVendas`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(80) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Armazenar dados dos clientes.';


-- -----------------------------------------------------
-- Table `RafaelVendas`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RafaelVendas`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` LONGTEXT NULL,
  `quantidade` INT NULL,
  `precoVenda` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Armazenar dados dos produtos';


-- -----------------------------------------------------
-- Table `RafaelVendas`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RafaelVendas`.`vendedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `salarioFixo` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RafaelVendas`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RafaelVendas`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataVenda` TIMESTAMP NULL,
  `notaFiscal` VARCHAR(45) NULL,
  `valorTotal` DECIMAL(10,2) NULL,
  `cliente_id` INT NOT NULL,
  `vendedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venda_cliente_idx` (`cliente_id` ASC),
  INDEX `fk_venda_vendedor1_idx` (`vendedor_id` ASC),
  CONSTRAINT `fk_venda_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `RafaelVendas`.`cliente` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_venda_vendedor1`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `RafaelVendas`.`vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Armazenar dados da venda';


-- -----------------------------------------------------
-- Table `RafaelVendas`.`itensVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RafaelVendas`.`itensVenda` (
  `produto_id` INT NOT NULL,
  `venda_id` INT NOT NULL,
  `quantidade` INT NULL,
  `precoVenda` DECIMAL(10,2) NULL,
  PRIMARY KEY (`produto_id`, `venda_id`),
  INDEX `fk_produto_has_venda_venda1_idx` (`venda_id` ASC),
  INDEX `fk_produto_has_venda_produto1_idx` (`produto_id` ASC),
  CONSTRAINT `fk_produto_has_venda_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `RafaelVendas`.`produto` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_produto_has_venda_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `RafaelVendas`.`venda` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
COMMENT = 'Armazenar produtos da venda';


-- -----------------------------------------------------
-- Table `RafaelVendas`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RafaelVendas`.`fornecedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `empresa` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;